# ---------- Listeners ----------
# MQTT classique
listener 1883 
protocol mqtt
 
# MQTT over WebSockets
listener 9001
protocol websockets
 
# Listener interne réservé au health check Docker
listener 8080 127.0.0.1

# ---------- Sécurité ----------
allow_anonymous false
password_file /mosquitto/config/passwd

# ---------- Persistance ----------
persistence true
persistence_location /mosquitto/data/
autosave_interval 300

# ---------- Logs ----------
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
connection_messages true

# ---------- ACL ----------
acl_file /mosquitto/acl