[[inputs.mqtt_consumer]]
  servers = [ "tcp://<broker_ip>:1883" ]
  topics = [ "test1/#", "test2/+/topic" ]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
  data_format = "influx"

[[outputs.health]]
  service_address = "http://:8080"
  default_status = 503  # Returns 503 until the first metric arrives
  max_time_between_metrics = "10s"